import {
  Activity,
  Anchor,
  Archive,
  Award,
  Banknote,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  CircleCheck,
  CircleDot,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Coins,
  Compass,
  Contact,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Droplet,
  Eye,
  Factory,
  Files,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gem,
  Gift,
  GitBranch,
  Globe,
  Goal,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Heart,
  Home,
  Hourglass,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  List,
  Lock,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Phone,
  PhoneCall,
  PieChart,
  PiggyBank,
  Pin,
  Plane,
  Receipt,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  StickyNote,
  Store,
  Sun,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  Tractor,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Umbrella,
  User,
  UserPlus,
  Users,
  Video,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react"

/**
 * Concept/field display glyphs. A single stored string encodes either source:
 *   • emoji → the literal grapheme, e.g. "🏢"
 *   • icon  → `lucide:<Name>`, e.g. "lucide:Building2"
 * Rendered by {@link ConceptIcon}; chosen via the IconPicker. The icon set is a
 * curated, explicitly-imported subset of lucide (tree-shaken; no dynamic import).
 */

export const ICON_PREFIX = "lucide:"

/** Curated lucide registry, keyed by the exact export name used in `lucide:<Name>`. */
export const ICONS: Record<string, LucideIcon> = {
  Building2,
  Building,
  Users,
  User,
  UserPlus,
  Contact,
  Briefcase,
  Handshake,
  FileText,
  Files,
  Folder,
  ClipboardList,
  NotebookPen,
  StickyNote,
  BookOpen,
  Mail,
  Send,
  MessageSquare,
  Phone,
  PhoneCall,
  Bell,
  Calendar,
  CalendarCheck,
  Clock,
  Timer,
  Hourglass,
  DollarSign,
  Banknote,
  CreditCard,
  Receipt,
  Wallet,
  PiggyBank,
  Coins,
  Landmark,
  TrendingUp,
  TrendingDown,
  BarChart3,
  LineChart,
  PieChart,
  Activity,
  Target,
  Goal,
  Trophy,
  Award,
  Medal,
  Star,
  Heart,
  Flag,
  Bookmark,
  Tag,
  Tags,
  Hash,
  Link,
  Globe,
  MapPin,
  Map,
  Compass,
  Rocket,
  Zap,
  Flame,
  Sparkles,
  Lightbulb,
  Shield,
  ShieldCheck,
  Lock,
  Key,
  CircleCheck,
  CircleDot,
  TriangleAlert,
  Info,
  Settings,
  Wrench,
  Hammer,
  Package,
  Truck,
  ShoppingCart,
  ShoppingBag,
  Store,
  Factory,
  Tractor,
  Shapes,
  Box,
  Boxes,
  Layers,
  List,
  LayoutGrid,
  Database,
  Server,
  Cloud,
  Code,
  Terminal,
  GitBranch,
  Smile,
  Coffee,
  Gift,
  PartyPopper,
  ThumbsUp,
  Eye,
  Search,
  Filter,
  Pin,
  Paperclip,
  Image,
  Camera,
  Video,
  Mic,
  Headphones,
  Music,
  Palette,
  Crown,
  Gem,
  Anchor,
  Plane,
  Car,
  Sun,
  Moon,
  Leaf,
  TreePine,
  Mountain,
  Droplet,
  Snowflake,
  Umbrella,
  Inbox,
  Archive,
  Megaphone,
  Home,
}

/** Ordered icon names for the picker grid (registry insertion order). */
export const ICON_NAMES: ReadonlyArray<string> = Object.keys(ICONS)

/** Fallback glyph shown for a concept that hasn't chosen an icon of its own. */
export const DEFAULT_CONCEPT_ICON = `${ICON_PREFIX}Shapes`

/**
 * Curated emoji set with search keywords (CRM/business-leaning, grouped by
 * theme). `kw` feeds the picker's filter; the leading word is also a label.
 */
export const EMOJIS: ReadonlyArray<{ readonly char: string; readonly kw: string }> = [
  // org / people
  { char: "🏢", kw: "building office company org" },
  { char: "🏠", kw: "house home" },
  { char: "🏬", kw: "store department building" },
  { char: "🏭", kw: "factory industry" },
  { char: "🏦", kw: "bank finance" },
  { char: "🏛️", kw: "institution government landmark" },
  { char: "👤", kw: "person user contact silhouette" },
  { char: "👥", kw: "people users team group" },
  { char: "🧑‍💼", kw: "office worker professional employee" },
  { char: "👔", kw: "necktie business suit" },
  { char: "🤝", kw: "handshake deal agreement partner" },
  { char: "🧑‍🤝‍🧑", kw: "people partners team" },
  { char: "👑", kw: "crown king vip premium" },
  { char: "🦸", kw: "hero champion" },
  // documents / writing
  { char: "📄", kw: "document page file" },
  { char: "📃", kw: "document curl page" },
  { char: "📝", kw: "memo note edit writing" },
  { char: "📋", kw: "clipboard list tasks" },
  { char: "📑", kw: "bookmark tabs documents" },
  { char: "📂", kw: "folder open files" },
  { char: "📁", kw: "folder files" },
  { char: "🗂️", kw: "dividers index card organize" },
  { char: "📌", kw: "pin pushpin location" },
  { char: "📎", kw: "paperclip attachment" },
  { char: "✏️", kw: "pencil edit write" },
  { char: "🖊️", kw: "pen write" },
  { char: "📚", kw: "books library knowledge" },
  { char: "📖", kw: "open book read" },
  { char: "🔖", kw: "bookmark tag label" },
  { char: "🏷️", kw: "label tag price" },
  // money / commerce
  { char: "💰", kw: "money bag wealth revenue" },
  { char: "💵", kw: "dollar cash money" },
  { char: "💴", kw: "yen cash money" },
  { char: "💶", kw: "euro cash money" },
  { char: "💷", kw: "pound cash money" },
  { char: "💳", kw: "credit card payment" },
  { char: "🧾", kw: "receipt invoice bill" },
  { char: "🪙", kw: "coin money token" },
  { char: "🐷", kw: "piggy bank savings" },
  { char: "📈", kw: "chart up growth trending revenue" },
  { char: "📉", kw: "chart down decline loss" },
  { char: "📊", kw: "bar chart analytics stats" },
  { char: "🛒", kw: "cart shopping purchase" },
  { char: "🛍️", kw: "shopping bags retail" },
  { char: "💸", kw: "money wings spend expense" },
  { char: "🏆", kw: "trophy win award champion" },
  // time
  { char: "📅", kw: "calendar date schedule" },
  { char: "📆", kw: "calendar tear-off date" },
  { char: "🗓️", kw: "calendar spiral planner" },
  { char: "⏰", kw: "alarm clock time" },
  { char: "⏱️", kw: "stopwatch timer" },
  { char: "⏳", kw: "hourglass time waiting" },
  { char: "🕐", kw: "clock time" },
  // status / signals
  { char: "✅", kw: "check done complete success" },
  { char: "☑️", kw: "checkbox checked done" },
  { char: "✔️", kw: "check mark done" },
  { char: "❌", kw: "cross x no fail" },
  { char: "⭐", kw: "star favorite featured" },
  { char: "🌟", kw: "glowing star special" },
  { char: "🔥", kw: "fire hot trending flame" },
  { char: "⚡", kw: "lightning fast energy zap" },
  { char: "💡", kw: "idea lightbulb insight" },
  { char: "🚀", kw: "rocket launch growth fast" },
  { char: "🎯", kw: "target goal aim" },
  { char: "🚩", kw: "flag milestone marker" },
  { char: "🏁", kw: "checkered flag finish goal" },
  { char: "❤️", kw: "heart love favorite" },
  { char: "⚠️", kw: "warning caution alert" },
  { char: "🔔", kw: "bell notification alert" },
  { char: "❓", kw: "question help unknown" },
  { char: "ℹ️", kw: "info information" },
  { char: "🆕", kw: "new badge" },
  { char: "🔒", kw: "lock secure private" },
  { char: "🔑", kw: "key access" },
  { char: "🛡️", kw: "shield protect security" },
  // comms
  { char: "✉️", kw: "envelope mail email" },
  { char: "📧", kw: "email mail" },
  { char: "📨", kw: "incoming mail message" },
  { char: "📬", kw: "mailbox inbox" },
  { char: "📞", kw: "phone call telephone" },
  { char: "☎️", kw: "telephone phone" },
  { char: "📱", kw: "mobile phone smartphone" },
  { char: "💬", kw: "speech chat message comment" },
  { char: "🗨️", kw: "speech bubble chat" },
  { char: "📣", kw: "megaphone announce broadcast" },
  { char: "📢", kw: "loudspeaker announce" },
  { char: "🔗", kw: "link chain url" },
  { char: "🌐", kw: "globe web internet world" },
  { char: "📡", kw: "satellite signal broadcast" },
  // tools / tech
  { char: "🔧", kw: "wrench tool fix settings" },
  { char: "🔨", kw: "hammer build tool" },
  { char: "🛠️", kw: "tools build maintenance" },
  { char: "⚙️", kw: "gear settings config" },
  { char: "🧰", kw: "toolbox tools" },
  { char: "💻", kw: "laptop computer code" },
  { char: "🖥️", kw: "desktop computer monitor" },
  { char: "🗄️", kw: "file cabinet archive database" },
  { char: "💾", kw: "save disk database" },
  { char: "🖨️", kw: "printer print" },
  { char: "🔌", kw: "plug integration connect" },
  { char: "🔋", kw: "battery power" },
  { char: "🐛", kw: "bug issue defect" },
  { char: "🧪", kw: "test experiment lab" },
  // objects / misc
  { char: "📦", kw: "package box product shipping" },
  { char: "🎁", kw: "gift present reward" },
  { char: "🚚", kw: "truck delivery shipping logistics" },
  { char: "✈️", kw: "plane travel flight" },
  { char: "🚗", kw: "car vehicle drive" },
  { char: "🗺️", kw: "map location route" },
  { char: "📍", kw: "pin location place" },
  { char: "🧭", kw: "compass direction navigate" },
  { char: "🔍", kw: "search magnify find" },
  { char: "👁️", kw: "eye view watch visibility" },
  { char: "🎨", kw: "art palette design creative" },
  { char: "📷", kw: "camera photo" },
  { char: "🎥", kw: "video movie camera" },
  { char: "🎤", kw: "microphone record voice" },
  { char: "🎧", kw: "headphones audio listen" },
  { char: "🎵", kw: "music note audio" },
  { char: "📌", kw: "pin marker" },
  { char: "🧩", kw: "puzzle piece module integration" },
  { char: "💎", kw: "gem diamond premium valuable" },
  { char: "⚓", kw: "anchor stable base" },
  { char: "🎉", kw: "party celebration win" },
  { char: "👍", kw: "thumbs up approve like" },
  { char: "☕", kw: "coffee break cafe" },
  { char: "🌱", kw: "seedling growth new" },
  { char: "🌿", kw: "leaf plant eco green" },
  { char: "🌲", kw: "tree evergreen nature" },
  { char: "⛰️", kw: "mountain peak goal" },
  { char: "☀️", kw: "sun day weather" },
  { char: "🌙", kw: "moon night" },
  { char: "💧", kw: "droplet water" },
  { char: "❄️", kw: "snowflake cold winter" },
  { char: "☂️", kw: "umbrella protection rain" },
  { char: "📥", kw: "inbox download receive" },
  { char: "📤", kw: "outbox upload send" },
  { char: "🗃️", kw: "card box archive records" },
  { char: "🏗️", kw: "construction build wip" },
  { char: "🏪", kw: "convenience store shop" },
  { char: "😀", kw: "smile happy face" },
  { char: "🙂", kw: "slight smile face" },
]

/**
 * Render a stored glyph value: a lucide component for `lucide:<Name>`, or the
 * literal string as an emoji. `null`/unknown → renders nothing (callers supply
 * their own fallback). `size` is in px (matches lucide's `size` and the emoji
 * font-size for visual parity).
 */
export function ConceptIcon({
  value,
  size = 16,
  className,
}: {
  value: string | null | undefined
  size?: number
  className?: string
}) {
  if (!value) return null
  if (value.startsWith(ICON_PREFIX)) {
    const Cmp = ICONS[value.slice(ICON_PREFIX.length)]
    return Cmp ? <Cmp size={size} className={className} /> : null
  }
  return (
    <span
      className={className}
      style={{ fontSize: size, lineHeight: 1 }}
      // Emoji is decorative here; the surrounding control carries the label.
      aria-hidden="true"
    >
      {value}
    </span>
  )
}
